### ISSUE TITLE
fix of an example in `lineare-abbildungen.tex`

### ISSUE THREAD

**Issue by LucaVazz** [karlstroetmann/Lineare-Algebra#9]
According to a comment in the lecture yesterday, line 148 in `lineare-abbildungen.tex` needs to get changed to 
>`$L\bigl( (x_1, x_2, x_3, \cdots) \bigr) := (x_2, x_3, x_4, \cdots)$`

**Comment by karlstroetmann** [comment]
Vielen Dank für den Hinweis!


> Luca Vazzano <notifications@github.com> hat am 6. Januar 2016 um 15:55
> geschrieben:
> 
> 
>  According to a comment in the lecture yesterday, line 148 in
> lineare-abbildungentex needs to get changed to
> 
>      > > 
> >      $L\bigl( (x_1, x_2, x_3, \cdots) \bigr) := (x_2, x_3, x_4, \cdots)$
> > 
> >  > 
>  —
>  Reply to this email directly or view it on GitHub
> <https://github.com/karlstroetmann/Lineare-Algebra/issues/9> .
> 
> 
> 



________________________________________________________________________

*Prof. Dr. Karl Stroetmann*

Professor für Lehraufgaben in der Angewandten Informatik

*Duale Hochschule Baden-Württemberg Mannheim*
*Angewandte Informatik*
Coblitzallee 1-9
68163 Mannheim

Tel.: +49 (0)621 4105 - 1376
Fax: +49 (0)621 4105 - 1194
Email: karl.stroetmann@dhbw-mannheim.de
Skype: karlstroetmann
